Repository celestiaorg/celestia-openrpc, pull requests merged in 2023-07, with the labels that each got.

#26 Update housekeeping.yml
  .github/workflows/housekeeping.yml
Labels: bug

#29 switch to cometbft
  go.mod
  go.sum
  types/core/core.go
  types/header/header.go
  types/namespace/random_namespace.go
  types/state/state.go
Labels: T:dependencies

#32 types: blob - extract createcommitment
  client_test.go
  go.mod
  go.sum
  types/appconsts/global_consts.go
  types/appconsts/v1/app_consts.go
  types/appconsts/versioned_consts.go
  types/blob/blob.go
  types/blob/blob_test.go
  types/blob/commitment.go
  types/blob/merkle.go
  types/blob/share_splitting.go
  types/core/core.go
  types/share/blob_share_commitment_rules.go
  types/share/info_byte.go
  types/share/padding.go
  types/share/powers_of_two.go
  types/share/reserved_bytes.go
  types/share/share.go
  types/share/share_builder.go
  types/share/split_sparse_shares.go
  types/share/utils.go
Labels: enhancement, T:dependencies
