Repository celestiaorg/celestia-openrpc, pull requests merged in 2023-09, with the labels that each got.

#50 readme: fix node api link
  README.md
Labels: documentation, T:documentation

#43 chore: bump go-header and go-fraud
  api.go
  go.mod
  go.sum
  types/header/header.go
Labels: T:dependencies

#51 feat: Add options to Blob Submit
  api.go
  client_test.go
Labels: enhancement, T:dependencies

#52 Update Namespaced shares fields use snake_case in JSON
  types/share/share.go
Labels: T:dependencies
